Part1
bobbybalow1/PFMCPP_Project1 pull request #1
Opened 2020-04-25 00:53 UTC by bobbybalow1

Finished assignment. Please review.

2020-04-25 16:46 UTC, matkatmusic requested changes

2020-04-25 16:46 UTC, matkatmusic commented on main.cpp
> +glass.wine();
`water` is not an action
`holdWater` is the action.
- [ ] revise

2020-04-25 16:46 UTC, matkatmusic commented on main.cpp
> +pan.veggies();
these are not actions
- [ ] revise

2020-04-25 16:46 UTC, matkatmusic commented on main.cpp
> +cuttingBoard.celery();
these are not actions.
- [ ] revise

2020-04-25 16:46 UTC, matkatmusic commented on main.cpp
> +asparagus.killWithFire();
some other object performs these actions on or to asparagus.  Asparagus does not perform these actions
- [ ] revise

2020-04-25 16:46 UTC, matkatmusic commented on main.cpp
> +cppHomework.push();
some other object performs these actions on cppHomework.  cppHomework does not perform these actions.
- [ ] revise

2020-04-29 16:13 UTC, matkatmusic approved these changes

2020-04-29 16:13 UTC, matkatmusic commented on main.cpp
> +email.trash();
an email **client** does these things

2020-04-29 16:13 UTC, merged

2020-04-30 11:47 UTC, bobbybalow1 commented on main.cpp
> +email.trash();
Good point! Thanks Chuck.